version: '3.7'

services:
  correlateme_db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: test
      POSTGRES_DB: dashboars
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "6432:5432"

volumes:
  database-data: