// Code generated by entc, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/DanielTitkov/dashboars/internal/repository/entgo/ent/item"
	"github.com/DanielTitkov/dashboars/internal/repository/entgo/ent/metric"
	"github.com/DanielTitkov/dashboars/internal/repository/entgo/ent/taskinstance"
)

// Item is the model entity for the Item schema.
type Item struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Value holds the value of the "value" field.
	Value float64 `json:"value,omitempty"`
	// Timestamp holds the value of the "timestamp" field.
	Timestamp time.Time `json:"timestamp,omitempty"`
	// Meta holds the value of the "meta" field.
	Meta map[string]interface{} `json:"meta,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ItemQuery when eager-loading is set.
	Edges               ItemEdges `json:"edges"`
	metric_items        *int
	task_instance_items *int
}

// ItemEdges holds the relations/edges for other nodes in the graph.
type ItemEdges struct {
	// TaskInstance holds the value of the task_instance edge.
	TaskInstance *TaskInstance `json:"task_instance,omitempty"`
	// Metric holds the value of the metric edge.
	Metric *Metric `json:"metric,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TaskInstanceOrErr returns the TaskInstance value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ItemEdges) TaskInstanceOrErr() (*TaskInstance, error) {
	if e.loadedTypes[0] {
		if e.TaskInstance == nil {
			// The edge task_instance was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: taskinstance.Label}
		}
		return e.TaskInstance, nil
	}
	return nil, &NotLoadedError{edge: "task_instance"}
}

// MetricOrErr returns the Metric value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ItemEdges) MetricOrErr() (*Metric, error) {
	if e.loadedTypes[1] {
		if e.Metric == nil {
			// The edge metric was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: metric.Label}
		}
		return e.Metric, nil
	}
	return nil, &NotLoadedError{edge: "metric"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Item) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case item.FieldMeta:
			values[i] = new([]byte)
		case item.FieldValue:
			values[i] = new(sql.NullFloat64)
		case item.FieldID:
			values[i] = new(sql.NullInt64)
		case item.FieldCreateTime, item.FieldUpdateTime, item.FieldTimestamp:
			values[i] = new(sql.NullTime)
		case item.ForeignKeys[0]: // metric_items
			values[i] = new(sql.NullInt64)
		case item.ForeignKeys[1]: // task_instance_items
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Item", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Item fields.
func (i *Item) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for j := range columns {
		switch columns[j] {
		case item.FieldID:
			value, ok := values[j].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			i.ID = int(value.Int64)
		case item.FieldCreateTime:
			if value, ok := values[j].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[j])
			} else if value.Valid {
				i.CreateTime = value.Time
			}
		case item.FieldUpdateTime:
			if value, ok := values[j].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[j])
			} else if value.Valid {
				i.UpdateTime = value.Time
			}
		case item.FieldValue:
			if value, ok := values[j].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[j])
			} else if value.Valid {
				i.Value = value.Float64
			}
		case item.FieldTimestamp:
			if value, ok := values[j].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field timestamp", values[j])
			} else if value.Valid {
				i.Timestamp = value.Time
			}
		case item.FieldMeta:
			if value, ok := values[j].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field meta", values[j])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &i.Meta); err != nil {
					return fmt.Errorf("unmarshal field meta: %w", err)
				}
			}
		case item.ForeignKeys[0]:
			if value, ok := values[j].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field metric_items", value)
			} else if value.Valid {
				i.metric_items = new(int)
				*i.metric_items = int(value.Int64)
			}
		case item.ForeignKeys[1]:
			if value, ok := values[j].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field task_instance_items", value)
			} else if value.Valid {
				i.task_instance_items = new(int)
				*i.task_instance_items = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryTaskInstance queries the "task_instance" edge of the Item entity.
func (i *Item) QueryTaskInstance() *TaskInstanceQuery {
	return (&ItemClient{config: i.config}).QueryTaskInstance(i)
}

// QueryMetric queries the "metric" edge of the Item entity.
func (i *Item) QueryMetric() *MetricQuery {
	return (&ItemClient{config: i.config}).QueryMetric(i)
}

// Update returns a builder for updating this Item.
// Note that you need to call Item.Unwrap() before calling this method if this Item
// was returned from a transaction, and the transaction was committed or rolled back.
func (i *Item) Update() *ItemUpdateOne {
	return (&ItemClient{config: i.config}).UpdateOne(i)
}

// Unwrap unwraps the Item entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (i *Item) Unwrap() *Item {
	tx, ok := i.config.driver.(*txDriver)
	if !ok {
		panic("ent: Item is not a transactional entity")
	}
	i.config.driver = tx.drv
	return i
}

// String implements the fmt.Stringer.
func (i *Item) String() string {
	var builder strings.Builder
	builder.WriteString("Item(")
	builder.WriteString(fmt.Sprintf("id=%v", i.ID))
	builder.WriteString(", create_time=")
	builder.WriteString(i.CreateTime.Format(time.ANSIC))
	builder.WriteString(", update_time=")
	builder.WriteString(i.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", value=")
	builder.WriteString(fmt.Sprintf("%v", i.Value))
	builder.WriteString(", timestamp=")
	builder.WriteString(i.Timestamp.Format(time.ANSIC))
	builder.WriteString(", meta=")
	builder.WriteString(fmt.Sprintf("%v", i.Meta))
	builder.WriteByte(')')
	return builder.String()
}

// Items is a parsable slice of Item.
type Items []*Item

func (i Items) config(cfg config) {
	for _i := range i {
		i[_i].config = cfg
	}
}
