// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DanielTitkov/dashboars/internal/repository/entgo/ent/task"
	"github.com/DanielTitkov/dashboars/internal/repository/entgo/ent/tasktag"
)

// TaskTagCreate is the builder for creating a TaskTag entity.
type TaskTagCreate struct {
	config
	mutation *TaskTagMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (ttc *TaskTagCreate) SetCreateTime(t time.Time) *TaskTagCreate {
	ttc.mutation.SetCreateTime(t)
	return ttc
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (ttc *TaskTagCreate) SetNillableCreateTime(t *time.Time) *TaskTagCreate {
	if t != nil {
		ttc.SetCreateTime(*t)
	}
	return ttc
}

// SetUpdateTime sets the "update_time" field.
func (ttc *TaskTagCreate) SetUpdateTime(t time.Time) *TaskTagCreate {
	ttc.mutation.SetUpdateTime(t)
	return ttc
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (ttc *TaskTagCreate) SetNillableUpdateTime(t *time.Time) *TaskTagCreate {
	if t != nil {
		ttc.SetUpdateTime(*t)
	}
	return ttc
}

// SetTitle sets the "title" field.
func (ttc *TaskTagCreate) SetTitle(s string) *TaskTagCreate {
	ttc.mutation.SetTitle(s)
	return ttc
}

// SetDescription sets the "description" field.
func (ttc *TaskTagCreate) SetDescription(s string) *TaskTagCreate {
	ttc.mutation.SetDescription(s)
	return ttc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ttc *TaskTagCreate) SetNillableDescription(s *string) *TaskTagCreate {
	if s != nil {
		ttc.SetDescription(*s)
	}
	return ttc
}

// SetDisplay sets the "display" field.
func (ttc *TaskTagCreate) SetDisplay(b bool) *TaskTagCreate {
	ttc.mutation.SetDisplay(b)
	return ttc
}

// SetNillableDisplay sets the "display" field if the given value is not nil.
func (ttc *TaskTagCreate) SetNillableDisplay(b *bool) *TaskTagCreate {
	if b != nil {
		ttc.SetDisplay(*b)
	}
	return ttc
}

// SetMeta sets the "meta" field.
func (ttc *TaskTagCreate) SetMeta(m map[string]interface{}) *TaskTagCreate {
	ttc.mutation.SetMeta(m)
	return ttc
}

// AddTaskIDs adds the "tasks" edge to the Task entity by IDs.
func (ttc *TaskTagCreate) AddTaskIDs(ids ...int) *TaskTagCreate {
	ttc.mutation.AddTaskIDs(ids...)
	return ttc
}

// AddTasks adds the "tasks" edges to the Task entity.
func (ttc *TaskTagCreate) AddTasks(t ...*Task) *TaskTagCreate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return ttc.AddTaskIDs(ids...)
}

// Mutation returns the TaskTagMutation object of the builder.
func (ttc *TaskTagCreate) Mutation() *TaskTagMutation {
	return ttc.mutation
}

// Save creates the TaskTag in the database.
func (ttc *TaskTagCreate) Save(ctx context.Context) (*TaskTag, error) {
	var (
		err  error
		node *TaskTag
	)
	ttc.defaults()
	if len(ttc.hooks) == 0 {
		if err = ttc.check(); err != nil {
			return nil, err
		}
		node, err = ttc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TaskTagMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ttc.check(); err != nil {
				return nil, err
			}
			ttc.mutation = mutation
			if node, err = ttc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ttc.hooks) - 1; i >= 0; i-- {
			if ttc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ttc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ttc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ttc *TaskTagCreate) SaveX(ctx context.Context) *TaskTag {
	v, err := ttc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ttc *TaskTagCreate) Exec(ctx context.Context) error {
	_, err := ttc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ttc *TaskTagCreate) ExecX(ctx context.Context) {
	if err := ttc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ttc *TaskTagCreate) defaults() {
	if _, ok := ttc.mutation.CreateTime(); !ok {
		v := tasktag.DefaultCreateTime()
		ttc.mutation.SetCreateTime(v)
	}
	if _, ok := ttc.mutation.UpdateTime(); !ok {
		v := tasktag.DefaultUpdateTime()
		ttc.mutation.SetUpdateTime(v)
	}
	if _, ok := ttc.mutation.Display(); !ok {
		v := tasktag.DefaultDisplay
		ttc.mutation.SetDisplay(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ttc *TaskTagCreate) check() error {
	if _, ok := ttc.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "TaskTag.create_time"`)}
	}
	if _, ok := ttc.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "TaskTag.update_time"`)}
	}
	if _, ok := ttc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "TaskTag.title"`)}
	}
	if v, ok := ttc.mutation.Title(); ok {
		if err := tasktag.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "TaskTag.title": %w`, err)}
		}
	}
	if v, ok := ttc.mutation.Description(); ok {
		if err := tasktag.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "TaskTag.description": %w`, err)}
		}
	}
	if _, ok := ttc.mutation.Display(); !ok {
		return &ValidationError{Name: "display", err: errors.New(`ent: missing required field "TaskTag.display"`)}
	}
	return nil
}

func (ttc *TaskTagCreate) sqlSave(ctx context.Context) (*TaskTag, error) {
	_node, _spec := ttc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ttc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ttc *TaskTagCreate) createSpec() (*TaskTag, *sqlgraph.CreateSpec) {
	var (
		_node = &TaskTag{config: ttc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: tasktag.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tasktag.FieldID,
			},
		}
	)
	if value, ok := ttc.mutation.CreateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: tasktag.FieldCreateTime,
		})
		_node.CreateTime = value
	}
	if value, ok := ttc.mutation.UpdateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: tasktag.FieldUpdateTime,
		})
		_node.UpdateTime = value
	}
	if value, ok := ttc.mutation.Title(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tasktag.FieldTitle,
		})
		_node.Title = value
	}
	if value, ok := ttc.mutation.Description(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: tasktag.FieldDescription,
		})
		_node.Description = value
	}
	if value, ok := ttc.mutation.Display(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: tasktag.FieldDisplay,
		})
		_node.Display = value
	}
	if value, ok := ttc.mutation.Meta(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: tasktag.FieldMeta,
		})
		_node.Meta = value
	}
	if nodes := ttc.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   tasktag.TasksTable,
			Columns: tasktag.TasksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: task.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TaskTagCreateBulk is the builder for creating many TaskTag entities in bulk.
type TaskTagCreateBulk struct {
	config
	builders []*TaskTagCreate
}

// Save creates the TaskTag entities in the database.
func (ttcb *TaskTagCreateBulk) Save(ctx context.Context) ([]*TaskTag, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ttcb.builders))
	nodes := make([]*TaskTag, len(ttcb.builders))
	mutators := make([]Mutator, len(ttcb.builders))
	for i := range ttcb.builders {
		func(i int, root context.Context) {
			builder := ttcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskTagMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ttcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ttcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ttcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ttcb *TaskTagCreateBulk) SaveX(ctx context.Context) []*TaskTag {
	v, err := ttcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ttcb *TaskTagCreateBulk) Exec(ctx context.Context) error {
	_, err := ttcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ttcb *TaskTagCreateBulk) ExecX(ctx context.Context) {
	if err := ttcb.Exec(ctx); err != nil {
		panic(err)
	}
}
