// Code generated by entc, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/DanielTitkov/dashboars/internal/repository/entgo/ent/tasktag"
)

// TaskTag is the model entity for the TaskTag schema.
type TaskTag struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Display holds the value of the "display" field.
	Display bool `json:"display,omitempty"`
	// Meta holds the value of the "meta" field.
	Meta map[string]interface{} `json:"meta,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TaskTagQuery when eager-loading is set.
	Edges TaskTagEdges `json:"edges"`
}

// TaskTagEdges holds the relations/edges for other nodes in the graph.
type TaskTagEdges struct {
	// Tasks holds the value of the tasks edge.
	Tasks []*Task `json:"tasks,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TasksOrErr returns the Tasks value or an error if the edge
// was not loaded in eager-loading.
func (e TaskTagEdges) TasksOrErr() ([]*Task, error) {
	if e.loadedTypes[0] {
		return e.Tasks, nil
	}
	return nil, &NotLoadedError{edge: "tasks"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TaskTag) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case tasktag.FieldMeta:
			values[i] = new([]byte)
		case tasktag.FieldDisplay:
			values[i] = new(sql.NullBool)
		case tasktag.FieldID:
			values[i] = new(sql.NullInt64)
		case tasktag.FieldTitle, tasktag.FieldDescription:
			values[i] = new(sql.NullString)
		case tasktag.FieldCreateTime, tasktag.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type TaskTag", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TaskTag fields.
func (tt *TaskTag) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tasktag.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			tt.ID = int(value.Int64)
		case tasktag.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				tt.CreateTime = value.Time
			}
		case tasktag.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				tt.UpdateTime = value.Time
			}
		case tasktag.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				tt.Title = value.String
			}
		case tasktag.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				tt.Description = value.String
			}
		case tasktag.FieldDisplay:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field display", values[i])
			} else if value.Valid {
				tt.Display = value.Bool
			}
		case tasktag.FieldMeta:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field meta", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &tt.Meta); err != nil {
					return fmt.Errorf("unmarshal field meta: %w", err)
				}
			}
		}
	}
	return nil
}

// QueryTasks queries the "tasks" edge of the TaskTag entity.
func (tt *TaskTag) QueryTasks() *TaskQuery {
	return (&TaskTagClient{config: tt.config}).QueryTasks(tt)
}

// Update returns a builder for updating this TaskTag.
// Note that you need to call TaskTag.Unwrap() before calling this method if this TaskTag
// was returned from a transaction, and the transaction was committed or rolled back.
func (tt *TaskTag) Update() *TaskTagUpdateOne {
	return (&TaskTagClient{config: tt.config}).UpdateOne(tt)
}

// Unwrap unwraps the TaskTag entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tt *TaskTag) Unwrap() *TaskTag {
	tx, ok := tt.config.driver.(*txDriver)
	if !ok {
		panic("ent: TaskTag is not a transactional entity")
	}
	tt.config.driver = tx.drv
	return tt
}

// String implements the fmt.Stringer.
func (tt *TaskTag) String() string {
	var builder strings.Builder
	builder.WriteString("TaskTag(")
	builder.WriteString(fmt.Sprintf("id=%v", tt.ID))
	builder.WriteString(", create_time=")
	builder.WriteString(tt.CreateTime.Format(time.ANSIC))
	builder.WriteString(", update_time=")
	builder.WriteString(tt.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", title=")
	builder.WriteString(tt.Title)
	builder.WriteString(", description=")
	builder.WriteString(tt.Description)
	builder.WriteString(", display=")
	builder.WriteString(fmt.Sprintf("%v", tt.Display))
	builder.WriteString(", meta=")
	builder.WriteString(fmt.Sprintf("%v", tt.Meta))
	builder.WriteByte(')')
	return builder.String()
}

// TaskTags is a parsable slice of TaskTag.
type TaskTags []*TaskTag

func (tt TaskTags) config(cfg config) {
	for _i := range tt {
		tt[_i].config = cfg
	}
}
