env: dev
db:
  uri: "host=localhost port=6432 user=test dbname=dashboars password=pass sslmode=disable"
  driver: postgres
server:
  port: 8000
  host: "0.0.0.0"
task:
  defaultSchedule: "1d"
  defaultRetryNumber: 3
  defaultRetryDelay: "15s"
  maxConcurrency: 10
app:
  defaultTaskPageLimit: 10
  systemSummaryInterval: 10 # minutes
  systemSummaryTimeout: 100 # milliseconds
auth:
  exp: 7200 # hours
  secret: secret-key
data:
  presets:
    taskPresetsPaths: 
      - ./data/presets/tasks.random.json
      - ./data/presets/tasks.failing.json
external:
  telegram:
    telegramTo: 99999
    telegramToken: "9999:AAAAAAAAA"