# template to substitute with actual values
env: deploy
db:
  uri: "host={{db_host}} port={{db_port}} user={{db_user}} dbname={{db_name}} password={{db_password}} sslmode=require"
  driver: postgres
server:
  port: 8000
  host: "0.0.0.0"
task:
  defaultSchedule: "1d"
  defaultRetryNumber: 3
  defaultRetryDelay: "300s"
  maxConcurrency: 50
app:
  systemSummaryInterval: 5 # minutes
  systemSummaryTimeout: 500 # milliseconds
data:
  presets:
    taskPresetsPaths: 
      # - ./data/presets/tasks.random.json
      # - ./data/presets/tasks.failing.json
      - ./data/presets/tasks.parser.json
external:
  telegram:
    telegramTo: {{telegram_to}}
    telegramToken: {{telegram_token}}